####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 244
  unit_system: imperial
  time_zone: !secret time_zone
  whitelist_external_dirs:
    - /config
    - /share

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

#https://www.home-assistant.io/components/climate/
climate:
  - platform: zwave

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/components/opengarage/
cover:
  platform: opengarage
  covers:
      garage:
        host:  192.168.1.18
        device_key: !secret device_key
        name: Garage Door

#https://github.com/custom-components/custom_updater
custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/MizterB/lovelace-secondaryinfo-entity-row/master/custom_cards.json
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
  component_urls:
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json

#https://www.home-assistant.io/components/downloader/
downloader:
  download_dir: /share

#https://www.home-assistant.io/hassio/
hassio:

#https://home-assistant.io/components/history/
history:

#https://home-assistant.io/components/http/
http:
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 2
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#https://home-assistant.io/components/logger/
logger:
  default: error

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml

#https://home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/components/system_health/
system_health:

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor.yaml
frontend: !include frontend.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
ios: !include ios.yaml
light: !include lights.yaml
notify: !include notification.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
zone: !include zones.yaml

####################################################
#                                                  #
#               Alexa Media                        #
#                                                  #
####################################################

#https://github.com/keatontaylor/alexa_media_player
alexa_media:
  accounts:
    - email: !secret notification_recipient
      password: !secret amazon
      url: amazon.com

####################################################
#                                                  #
#               EMULATED HUE                       #
#                                                  #
####################################################

#https://home-assistant.io/components/emulated_hue/
emulated_hue:
  expose_by_default: false
  entities:
    light.yeelightrgb2:
      hidden: false
      name: Notification
    group.living_room_lamps:
      name: Lamps
      hidden: false
    switch.receiverpower:
      hidden: false
      name: Amplifier
    switch.tvpower:
      hidden: false
      name: TV
    script.normallight:
      hidden: false
      name: normal light
    script.volumedown:
      hidden: false
      name: Volume Down
    script.volumeup:
      hidden: false
      name: Volume Up
    input_boolean.feeddog:
      hidden: false
      name: feeddog

####################################################
#                                                  #
#                    GROUP                         #
#                                                  #
####################################################

#https://www.home-assistant.io/components/group/
group:
  outside_lights:
    - light.yeelight1
    - light.yeelight2
    - light.yeelight3
    - light.yeelight4
  front_lights:
    - light.yeelight1
    - light.yeelight3
    - light.yeelight4
  adam_home_presence:
    - device_tracker.adams_iphone #GPS
    - device_tracker.adam_s_iphone #WiFi
  amy_home_presence:
    - device_tracker.amys_iphone #GPS
    - device_tracker.amy_s_iphone #WiFi
  home_presence:
    - device_tracker.adams_iphone #GPS
    - device_tracker.adam_s_iphone #WiFi
    - device_tracker.amys_iphone #GPS
    - device_tracker.amy_s_iphone #WiFi
  living_room_lamps:
    - switch.basic1
    - light.yeelightrgb2

####################################################
#                                                  #
#                   OPENUV                         #
#                                                  #
####################################################

#https://www.home-assistant.io/components/openuv/
openuv:
  api_key: !secret openuv
  binary_sensors:
    monitored_conditions:
      - uv_protection_window
  sensors:
    monitored_conditions:
      - current_ozone_level
      - current_uv_index
      - current_uv_level
      - max_uv_index
      - safe_exposure_time_type_3

####################################################
#                                                  #
#                   SPEETEST                       #
#                                                  #
####################################################

#https://www.home-assistant.io/components/speedtestdotnet/
speedtestdotnet:
  server_id: 1776
  monitored_conditions:
    - download
    - upload

####################################################
#                                                  #
#                TRADFRI HUB                       #
#                                                  #
####################################################

#https://home-assistant.io/components/tradfri/
tradfri:
  host: 192.168.1.20
  allow_tradfri_groups: false

####################################################
#                                                  #
#                   WEATHER                        #
#                                                  #
####################################################

#https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

####################################################
#                                                  #
#                     YEELIGHTS                    #
#                                                  #
####################################################

#https://home-assistant.io/components/light.yeelight/

yeelight:
  devices:
    192.168.1.10:
      name: Yeelight1
    192.168.1.11:
      name: Yeelight2
    192.168.1.12:
      name: Yeelight3
    192.168.1.26:
      name: Yeelight4
    192.168.1.28:
      name: Yeelight5
    192.168.1.25:
      name: YeelightRGB2

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
